---
- name: LSF
  hosts: lsf1
  become: yes
  vars_files:
    - proxy.yml
  environment: "{{ proxy_env }}"
  roles:
    # DON'T UPDATE OS BEFORE INSTALLING THE LSF.
    # - ../ansible_common/common
    - ../ansible_common/lsf
